### ISSUE TITLE
[question]web3 trace block

### ISSUE THREAD

**Issue by itcuihao** [umbracle/ethgo#146]
hi, How do call this function `w3.parity.traceBlock(14067789)`

**Comment by ferranbt** [comment]
As of now this library does not support any `parity` endpoints and I am not sure if it will be since I think OpenEthereum (parity) is being deprecated. With respect to debugging endpoints, the only one it supports right now is [TraceTransaction](https://github.com/umbracle/go-web3/blob/master/jsonrpc/debug.go#L31).
