### ISSUE TITLE
Panic when when creating a transaction from a web3 contract.

### ISSUE THREAD

**Issue by 0xKitsune** [umbracle/ethgo#93]
I am running into an issue when creating a transaction from a web3 contract. While reading through the docs, I noticed that you could create a transaction through the Txn() method on a contract. When doing this, I receive a ```panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc1ee58]``` error.  

Here is my code that produces the error.

```
	client, err := jsonrpc.NewClient(URL)
	if err != nil {
		fmt.Println(err)
                os.Exit(1)
	}

	//create a web3 contract
	//initialize the contract abi
	abi, err := abi.NewABI(abiString)
	if err != nil {
		fmt.Println(err)
                os.Exit(1)
	}

	//initialize the contract instance
	contractAddress := web3.HexToAddress(contractAddressHex)
	contractInstance := contract.NewContract(contractAddress, abi, client)

	//create a transaction to call the approve function on the contract address
	// Solidity function: approve(address spender, uint256 amount) external returns (bool);
	transaction := contractInstance.Txn("approve", spenderWalletAddress, 99999999999999999)

```

When the program creates the transaction, it panics and throws the error mentioned above. Do you know if there is a way to fix this?

**Comment by D-Cous** [comment]
After forking the repo and some debugging, we were able to figure out that this was because there was not a from address set. It would be helpful to have error handling in the contract.Txn() function to indicate if there is not a from address set for the contract instance, or when creating the Txn, allow the user to pass in a from address. I can create a PR to add this functionality!

**Comment by ferranbt** [comment]
Hi, I have updated the library and the interaction with the contracts in #167. I am closing this issue since it involves the old API. Please try again with the new API and open a new issue if something does not work.

Sorry for not fixing this issue before, it took some time to think about the correct spec for contract interaction.
